# Generated by Django 3.0.3 on 2020-04-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200404_1930'),
        ('users', '0004_auto_20200405_0323'),
    ]

    operations = [
    ]
