# Generated by Django 3.0.3 on 2020-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeboard', '0002_auto_20200331_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='transaction_state',
            field=models.CharField(choices=[('in progress', 'in progress'), ('complete', 'complete')], default='in progress', max_length=50),
        ),
    ]
