# Generated by Django 3.0.3 on 2020-04-04 19:30

from django.db import migrations, models
import tradeboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeboard', '0003_auto_20200331_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='edition',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='ISBN',
            field=models.CharField(max_length=13, validators=[tradeboard.models.Post.validate_ISBN]),
        ),
        migrations.AlterField(
            model_name='post',
            name='transaction_state',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Complete', 'Complete')], default='In progress', max_length=50),
        ),
    ]
